-- 自動生成ファイル。手編集禁止。
-- 再生成: npm run registry:generate-seed （data/*.seed.ts を編集してから実行すること）

INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-01', NULL, 'frontend', 'Next.js単体', 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-01', NULL, 'backend', 'Next.js API Routes', 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-01', NULL, 'database', 'PostgreSQL', 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-01', NULL, 'auth', 'Supabase Auth', 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-01', NULL, 'hosting', 'Vercel', 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-01', NULL, 'monitoring', 'Vercel Analytics', 5);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-02', NULL, 'frontend', 'Laravel Blade', 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-02', NULL, 'backend', 'Laravel', 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-02', NULL, 'database', 'MySQL', 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-02', NULL, 'auth', 'Laravel標準認証', 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-02', NULL, 'hosting', 'AWS Lightsail', 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-03', NULL, 'frontend', 'React', 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-03', NULL, 'backend', 'NestJS', 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-03', NULL, 'database', 'PostgreSQL', 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-03', NULL, 'auth', 'Supabase Auth', 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-03', NULL, 'hosting', 'AWS / GCP', 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-03', NULL, 'monitoring', 'Sentry', 5);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-04', NULL, 'frontend', 'Next.js', 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-04', NULL, 'backend', 'FastAPI', 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-04', NULL, 'database', 'PostgreSQL', 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-04', NULL, 'auth', 'Supabase Auth', 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-04', NULL, 'hosting', 'Vercel＋Cloud Run', 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-05', NULL, 'frontend', 'React', 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-05', NULL, 'database', 'Supabase (Postgres)', 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-05', NULL, 'auth', 'Supabase Auth', 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-05', NULL, 'storage', 'Supabase Storage', 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-05', NULL, 'hosting', 'Vercel', 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-06', NULL, 'frontend', 'Flutter', 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-06', NULL, 'database', 'Firestore', 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-06', NULL, 'auth', 'Firebase Auth', 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-06', NULL, 'hosting', 'Firebase Hosting', 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-07', NULL, 'frontend', 'Blazor Server', 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-07', NULL, 'backend', 'ASP.NET Core', 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-07', NULL, 'database', 'Azure SQL', 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-07', NULL, 'auth', 'Entra ID', 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-07', NULL, 'hosting', 'Azure App Service', 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-07', NULL, 'monitoring', 'Azure Monitor', 5);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-08', NULL, 'frontend', 'Power Apps', 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-08', NULL, 'automation', 'Power Automate', 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-08', NULL, 'database', 'Dataverse / Azure SQL', 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-08', NULL, 'auth', 'Entra ID', 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-08', NULL, 'hosting', 'Microsoft 365 / Azure', 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-09', NULL, 'frontend', 'Next.js（軽量）', 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-09', NULL, 'backend', 'FastAPI', 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-09', NULL, 'database', 'PostgreSQL', 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-09', NULL, 'search', 'pgvector', 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-09', NULL, 'ai', 'RAGパイプライン（Python）', 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-09', NULL, 'auth', 'Supabase Auth', 5);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-09', NULL, 'hosting', 'Cloud Run', 6);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-10', NULL, 'frontend', 'Streamlit', 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-10', NULL, 'backend', 'Django', 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-10', NULL, 'database', 'PostgreSQL', 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-10', NULL, 'automation', 'Celery', 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-10', NULL, 'hosting', 'Cloud Run', 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-11', NULL, 'automation', 'n8n', 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-11', NULL, 'database', 'n8n内蔵DB＋連携先', 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-11', NULL, 'auth', 'n8n Basic Auth', 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-11', NULL, 'hosting', 'Docker（自社/Cloud Run）', 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-12', NULL, 'automation', 'Power Automate', 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-12', NULL, 'database', 'Dataverse', 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-12', NULL, 'auth', 'Entra ID', 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-12', NULL, 'hosting', 'Microsoft 365', 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-13', NULL, 'frontend', 'Flutter', 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-13', NULL, 'database', 'Supabase (Postgres)', 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-13', NULL, 'auth', 'Supabase Auth', 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-13', NULL, 'hosting', 'Firebase / Vercel', 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-14', NULL, 'frontend', 'Expo (PWA)', 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-14', NULL, 'backend', 'Cloud Functions', 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-14', NULL, 'database', 'Firestore', 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-14', NULL, 'auth', 'Firebase Auth', 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-14', NULL, 'hosting', 'Firebase Hosting', 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-15', NULL, 'frontend', 'Tauri', 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-15', NULL, 'backend', 'Tauriバックエンド (Rust)', 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-15', NULL, 'database', 'SQLite（ローカル）＋同期', 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-15', NULL, 'hosting', '店舗端末常駐', 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-16', NULL, 'frontend', 'Shopify管理画面', 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-16', NULL, 'backend', 'Cloud Functions', 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-16', NULL, 'database', 'Shopify＋自社DB (PostgreSQL)', 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-16', NULL, 'auth', 'Shopify Auth', 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'SP-16', NULL, 'hosting', 'Cloud Run', 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-01', 'react-vite', NULL, NULL, 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-01', 'shadcn-ui', NULL, NULL, 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-01', 'mui', NULL, NULL, 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-01', 'chakra-ui', NULL, NULL, 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-01', 'ant-design', NULL, NULL, 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-01', 'radix-ui', NULL, NULL, 5);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-01', 'tailwind-css', NULL, NULL, 6);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-01', 'bootstrap', NULL, NULL, 7);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-01', 'supabase-data-api', NULL, NULL, 8);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-01', 'supabase-edge-functions', NULL, NULL, 9);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-01', 'supabase-realtime', NULL, NULL, 10);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-01', 'supabase-postgresql', NULL, NULL, 11);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-01', 'supabase-auth', NULL, NULL, 12);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-01', 'supabase-storage', NULL, NULL, 13);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-01', 'vercel', NULL, NULL, 14);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-01', 'custom-dev', NULL, NULL, 15);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-01', 'ai-coding', NULL, NULL, 16);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-01', 'github-actions', NULL, NULL, 17);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-02', 'vue-vite', NULL, NULL, 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-02', 'vuetify', NULL, NULL, 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-02', 'tailwind-css', NULL, NULL, 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-02', 'bootstrap', NULL, NULL, 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-02', 'supabase-data-api', NULL, NULL, 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-02', 'supabase-auth', NULL, NULL, 5);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-02', 'supabase-storage', NULL, NULL, 6);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-02', 'vercel', NULL, NULL, 7);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-02', 'custom-dev', NULL, NULL, 8);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-02', 'github-actions', NULL, NULL, 9);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-03', 'nextjs', NULL, NULL, 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-03', 'shadcn-ui', NULL, NULL, 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-03', 'mui', NULL, NULL, 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-03', 'chakra-ui', NULL, NULL, 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-03', 'ant-design', NULL, NULL, 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-03', 'radix-ui', NULL, NULL, 5);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-03', 'tailwind-css', NULL, NULL, 6);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-03', 'bootstrap', NULL, NULL, 7);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-03', 'nextjs-server-actions', NULL, NULL, 8);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-03', 'supabase-postgresql', NULL, NULL, 9);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-03', 'drizzle-orm', NULL, NULL, 10);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-03', 'supabase-auth', NULL, NULL, 11);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-03', 'supabase-storage', NULL, NULL, 12);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-03', 'vercel', NULL, NULL, 13);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-03', 'custom-dev', NULL, NULL, 14);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-03', 'ai-coding', NULL, NULL, 15);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-03', 'github-actions', NULL, NULL, 16);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-04', 'nextjs', NULL, NULL, 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-04', 'shadcn-ui', NULL, NULL, 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-04', 'mui', NULL, NULL, 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-04', 'chakra-ui', NULL, NULL, 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-04', 'ant-design', NULL, NULL, 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-04', 'radix-ui', NULL, NULL, 5);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-04', 'tailwind-css', NULL, NULL, 6);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-04', 'bootstrap', NULL, NULL, 7);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-04', 'postgresql', NULL, NULL, 8);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-04', 'prisma', NULL, NULL, 9);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-04', 'supabase-auth', NULL, NULL, 10);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-04', 'clerk', NULL, NULL, 11);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-04', 's3', NULL, NULL, 12);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-04', 'vercel', NULL, NULL, 13);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-04', 'railway', NULL, NULL, 14);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-04', 'custom-dev', NULL, NULL, 15);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-04', 'existing-saas', NULL, NULL, 16);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-04', 'github-actions', NULL, NULL, 17);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-04', 'sentry', NULL, NULL, 18);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-05', 'nextjs', NULL, NULL, 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-05', 'shadcn-ui', NULL, NULL, 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-05', 'mui', NULL, NULL, 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-05', 'chakra-ui', NULL, NULL, 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-05', 'ant-design', NULL, NULL, 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-05', 'radix-ui', NULL, NULL, 5);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-05', 'tailwind-css', NULL, NULL, 6);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-05', 'bootstrap', NULL, NULL, 7);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-05', 'cloud-functions', NULL, NULL, 8);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-05', 'firestore', NULL, NULL, 9);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-05', 'firebase-auth', NULL, NULL, 10);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-05', 'firebase-storage', NULL, NULL, 11);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-05', 'firebase-app-hosting', NULL, NULL, 12);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-05', 'custom-dev', NULL, NULL, 13);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-05', 'github-actions', NULL, NULL, 14);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-06', 'pwa', NULL, NULL, 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-06', 'tailwind-css', NULL, NULL, 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-06', 'bootstrap', NULL, NULL, 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-06', 'firestore', NULL, NULL, 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-06', 'firebase-auth', NULL, NULL, 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-06', 'firebase-storage', NULL, NULL, 5);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-06', 'firebase-hosting', NULL, NULL, 6);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-06', 'custom-dev', NULL, NULL, 7);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-06', 'github-actions', NULL, NULL, 8);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-07', 'nuxt', NULL, NULL, 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-07', 'vuetify', NULL, NULL, 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-07', 'tailwind-css', NULL, NULL, 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-07', 'bootstrap', NULL, NULL, 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-07', 'supabase-postgresql', NULL, NULL, 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-07', 'supabase-auth', NULL, NULL, 5);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-07', 'supabase-storage', NULL, NULL, 6);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-07', 'vercel', NULL, NULL, 7);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-07', 'custom-dev', NULL, NULL, 8);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-07', 'github-actions', NULL, NULL, 9);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-08', 'sveltekit', NULL, NULL, 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-08', 'tailwind-css', NULL, NULL, 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-08', 'bootstrap', NULL, NULL, 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-08', 'supabase-data-api', NULL, NULL, 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-08', 'drizzle-orm', NULL, NULL, 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-08', 'supabase-auth', NULL, NULL, 5);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-08', 'supabase-storage', NULL, NULL, 6);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-08', 'vercel', NULL, NULL, 7);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-08', 'custom-dev', NULL, NULL, 8);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-08', 'github-actions', NULL, NULL, 9);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-09', 'astro', NULL, NULL, 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-09', 'tailwind-css', NULL, NULL, 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-09', 'bootstrap', NULL, NULL, 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-09', 'custom-dev', NULL, NULL, 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-09', 'github-actions', NULL, NULL, 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-10', 'tailwind-css', NULL, NULL, 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-10', 'bootstrap', NULL, NULL, 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-10', 'hono', NULL, NULL, 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-10', 'drizzle-orm', NULL, NULL, 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-10', 'custom-dev', NULL, NULL, 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-10', 'github-actions', NULL, NULL, 5);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-11', 'tailwind-css', NULL, NULL, 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-11', 'bootstrap', NULL, NULL, 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-11', 'mongodb', NULL, NULL, 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-11', 'custom-dev', NULL, NULL, 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'WEB-11', 'github-actions', NULL, NULL, 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-01', 'tailwind-css', NULL, NULL, 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-01', 'bootstrap', NULL, NULL, 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-01', 'flutter', NULL, NULL, 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-01', 'cloud-functions', NULL, NULL, 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-01', 'firestore', NULL, NULL, 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-01', 'firebase-auth', NULL, NULL, 5);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-01', 'firebase-storage', NULL, NULL, 6);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-01', 'app-store-google-play', NULL, NULL, 7);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-01', 'custom-dev', NULL, NULL, 8);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-01', 'ai-coding', NULL, NULL, 9);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-01', 'github-actions', NULL, NULL, 10);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-02', 'tailwind-css', NULL, NULL, 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-02', 'bootstrap', NULL, NULL, 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-02', 'flutter', NULL, NULL, 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-02', 'supabase-edge-functions', NULL, NULL, 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-02', 'supabase-realtime', NULL, NULL, 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-02', 'supabase-postgresql', NULL, NULL, 5);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-02', 'supabase-auth', NULL, NULL, 6);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-02', 'supabase-storage', NULL, NULL, 7);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-02', 'app-store-google-play', NULL, NULL, 8);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-02', 'custom-dev', NULL, NULL, 9);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-02', 'github-actions', NULL, NULL, 10);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-03', 'tailwind-css', NULL, NULL, 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-03', 'bootstrap', NULL, NULL, 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-03', 'flutter', NULL, NULL, 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-03', 'firestore', NULL, NULL, 3);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-03', 'firebase-auth', NULL, NULL, 4);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-03', 'firebase-storage', NULL, NULL, 5);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-03', 'firebase-hosting', NULL, NULL, 6);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-03', 'app-store-google-play', NULL, NULL, 7);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-03', 'custom-dev', NULL, NULL, 8);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-03', 'github-actions', NULL, NULL, 9);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-04', 'tailwind-css', NULL, NULL, 0);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-04', 'bootstrap', NULL, NULL, 1);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-04', 'react-native-expo', NULL, NULL, 2);
INSERT INTO registry_stack_preset_items (release_id, preset_id, technology_id, role, label_override, sort_order) VALUES (1, 'MOB-04', 'cloud-functions', NULL, NULL, 3);
