-- 自動生成ファイル。手編集禁止。
-- 再生成: npm run registry:generate-seed （data/*.seed.ts を編集してから実行すること）

INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('cloud-run', 1, 'hosting', 'tool', 'Cloud Run', 'Docker化したFastAPIやWeb APIをGoogle Cloud上で公開する', '{"overview":"Dockerコンテナ化したアプリケーションを、Google Cloud上でサーバーレスに実行できるサービス。","fit":"FastAPIなどのPython APIをコンテナとして公開し、アクセス量に応じて自動でスケールさせたい場合に向く。","caution":"コンテナのビルド・管理が必要なため、PaaS的なサービスに比べ最初の設定はやや手間がかかる。","url":"https://cloud.google.com/run"}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 4);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('azure-app-service', 1, 'hosting', 'tool', 'Azure App Service', 'WebアプリやAPIをAzure上で公開・運用する', '{"overview":"Azure上でWebアプリやAPIを公開・運用できるマネージドサービス。","fit":"Azure環境で.NETやMicrosoft系の技術を使ったシステムを公開したい場合に向く。","caution":"他クラウドに比べ、Azure独自の設定・料金体系への理解が必要。","url":"https://azure.microsoft.com/en-us/products/app-service"}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 5);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('aws-cloudfront', 1, 'hosting', 'tool', 'Amazon CloudFront', 'Webコンテンツやファイルを世界各地へ高速配信する', '{"overview":"Amazon S3、API Gateway、ロードバランサーなどを配信元として、WebコンテンツやAPIを世界各地のエッジ拠点から配信するCDN。","fit":"画像・動画・静的ファイルなどを、世界中のユーザーへ高速に配信したい場合に向く。","caution":"キャッシュ設定を誤ると更新内容が反映されないことがあり、キャッシュ無効化の運用ルールが必要。","url":"https://aws.amazon.com/cloudfront/"}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 6);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('docker-compose', 1, 'hosting', 'tool', 'Docker Compose', '複数のアプリ、DB、ストレージを一つのサーバー上で管理する', '{"overview":"複数のコンテナ（アプリ・DB・ストレージなど）をまとめて定義・起動できるツール。","fit":"1台のサーバー上でアプリ一式を低コストにセルフホストしたい場合に向く。","caution":"複数サーバーへのスケールや自動復旧には対応しておらず、大規模運用にはKubernetes等の検討が必要。","url":"https://docs.docker.com/compose/"}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 7);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('caddy', 1, 'hosting', 'tool', 'Caddy', 'HTTPS化とリバースプロキシを簡単に設定する', '{"overview":"HTTPS化（証明書の自動取得・更新）とリバースプロキシ設定を簡単に行えるWebサーバー。","fit":"セルフホスト環境で、手間をかけずにSSL対応した公開URLを用意したい場合に向く。","caution":"Nginx等に比べ情報量・実績はやや少なく、高度なチューニングが必要な場合は情報収集に工夫が要る。","url":"https://caddyserver.com/"}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 8);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('kubernetes', 1, 'hosting', 'tool', 'Kubernetes', '複数サーバー上でアプリを自動配置し、障害時の復旧や拡張を行う', '{"overview":"複数サーバー上でコンテナを自動配置・スケール・障害復旧させる基盤。大規模システムの運用標準の一つ。","fit":"アクセス規模が大きく、高可用性が求められるシステムの本番運用に向く。","caution":"構築・運用の学習コストが高く、小〜中規模のシステムにはオーバースペックになりやすい。","url":"https://kubernetes.io/"}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 9);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('vps', 1, 'hosting', 'tool', 'VPS・クラウドVM', 'n8nや独自APIを常時稼働させる', '{"overview":"仮想専用サーバー。n8nや独自APIなど、常時稼働させたいプロセスを配置する基盤として使う。","fit":"サーバーレスでは実現しにくい常駐プロセス（ワークフローツールのサーバーなど）を動かしたい場合に向く。","caution":"OSやミドルウェアのアップデート・セキュリティ対応を自社で継続的に行う必要がある。"}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 10);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('app-store-google-play', 1, 'hosting', 'tool', 'App Store・Google Play', 'iOS・Androidアプリを利用者へ配布する', '{"overview":"iOS・Androidアプリをユーザーへ配布するための公式ストア。","fit":"モバイルアプリを一般ユーザー向けに正式配布したい場合には必須の経路。","caution":"審査基準への対応やリリースサイクルの管理が必要で、公開までに一定の期間がかかる。"}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 11);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('eas', 1, 'hosting', 'tool', 'EAS', 'Expo製のReact Nativeアプリをビルドし、アプリストアへ配布する', '{"overview":"Expo製のReact Nativeアプリを、クラウド上でビルドしてストアへ配布できるサービス（Expo Application Services）。","fit":"手元でネイティブビルド環境を用意せず、React Nativeアプリをストア配布したい場合に向く。","caution":"ビルドの実行回数や時間に応じたプランの確認が必要。","url":"https://docs.expo.dev/eas/"}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 12);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('onpremise-server', 1, 'hosting', 'tool', 'オンプレミスサーバー', '外部クラウドを利用せず、社内設備内でシステムを運用する', '{"overview":"外部のクラウドサービスを使わず、社内設備内に設置したサーバーでシステムを運用する形態。","fit":"データを外部に出せない規制や、既存の社内インフラを活用したい場合に向く。","caution":"サーバーの調達・保守・災害対策を自社で担う必要があり、運用負荷とコストが大きい。"}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 13);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('cloudflare-workers', 1, 'hosting', 'tool', 'Cloudflare Workers', 'API、Webアプリ、認証前処理、キャッシュ処理を世界各地のエッジ環境で実行する', '{"overview":"Cloudflareのグローバルネットワーク上で、JavaScript、TypeScriptなどの処理を実行できるサーバーレス基盤。","fit":"低遅延なAPI、Webhook、認証処理、画像変換、キャッシュ制御、軽量なフルスタックアプリに向く。","caution":"一般的なNode.jsサーバーとは実行環境や制限が異なる。利用するライブラリの互換性、CPU時間、メモリ、外部通信などの制限を確認する。","url":"https://developers.cloudflare.com/workers/"}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 14);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('custom-dev', 1, 'dev-approach', 'tool', '独自開発', '業務に合わせた管理画面、データ構造、処理ルールを個別に構築する', '{"overview":"既存パッケージに頼らず、業務要件に合わせて管理画面・データ構造・処理ルールを個別に設計・実装する開発方式。","fit":"業務フローの独自性が高く、既存SaaSでは業務に合わせきれない場合に向く。","caution":"開発・保守の工数が大きくなりやすく、要件の見極めと段階的な開発計画が重要。"}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 0);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('ai-coding', 1, 'dev-approach', 'tool', 'AIコーディング中心', 'AIにコード作成、修正、テストを支援させ、開発期間を短縮する', '{"overview":"AIにコードの生成・修正・テストなどを支援させながら開発を進める方式。特定の製品ではなく開発スタイル。","fit":"限られた人員・期間でMVPや初期構築を素早く進めたい場合に向く。","caution":"AIが生成したコードであっても、最終的な品質と権利は開発側が管理する。コードレビュー、テスト、依存ライブラリ確認、秘密情報の混入防止、セキュリティ診断を開発工程に組み込む必要がある。"}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 1);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('existing-saas', 1, 'dev-approach', 'tool', '既存SaaS連携', '認証、決済、メール、ファイル保管などを外部サービスで補う', '{"overview":"認証・決済・メール配信・ファイル保管といった機能を、自前実装せず既存の外部SaaSで補う方式。","fit":"開発リソースを独自の価値提供部分に集中させ、周辺機能は実績あるSaaSに任せたい場合に向く。","caution":"外部SaaSの障害・仕様変更・料金改定の影響を受けるため、利用規約や可用性の確認が必要。"}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 2);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('github-actions', 1, 'dev-approach', 'tool', 'GitHub Actions', 'テスト、ビルド、デプロイ、定期処理をGitHubへの更新に合わせて自動実行する', '{"overview":"GitHubリポジトリ内でCI/CDや各種自動処理を実行できるワークフロー機能。","fit":"コードの更新時にテストやビルドを実行し、Vercel、AWS、VPSなどへ自動デプロイしたい場合に向く。","caution":"秘密情報はGitHub Secretsなどで管理し、外部から取得したActionのバージョンを固定する。実行時間や同時実行数による料金も確認する。","url":"https://docs.github.com/en/actions"}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 3);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('sentry', 1, 'dev-approach', 'tool', 'Sentry', '本番環境のエラー、処理遅延、障害の影響範囲を確認する', '{"overview":"フロントエンド、バックエンド、モバイルアプリなどのエラー情報やパフォーマンス情報を収集・分析する監視サービス。","fit":"利用者の環境で発生したエラーを再現しにくいWebサービス、SaaS、モバイルアプリに向く。","caution":"個人情報や入力内容が意図せず送信されないよう、収集対象を設定する。イベント数が多い場合はサンプリングと料金管理も必要。","url":"https://sentry.io/"}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 4);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('kintone', 1, 'saas-product', 'saas', 'kintone', '業務アプリをノーコードで素早く作れる国産SaaS。承認フロー・帳票・権限管理が標準機能として揃っている', '{"strengths":["短期間で業務アプリを構築できる","承認フローが標準搭載","国内での導入実績が豊富"],"pricing":{"monthlyBaseFee":0,"monthlyPricePerUser":1500}}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 0);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('m365_power_platform', 1, 'saas-product', 'saas', 'Microsoft 365（SharePoint + Power Automate）', '既にMicrosoft 365を利用している場合、追加コストを抑えて承認フローや簡易業務アプリを構築できる', '{"strengths":["追加コストが少ない","Entra IDとシームレスに連携","Teams通知と統合できる"],"pricing":{"monthlyBaseFee":0,"monthlyPricePerUser":1500}}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 1);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('salesforce_sales_cloud', 1, 'saas-product', 'saas', 'Salesforce Sales Cloud', '商談・案件管理の定番SaaS。API連携やカスタムオブジェクトによる拡張性が高い', '{"strengths":["営業プロセス管理の実績が豊富","外部連携APIが充実","カスタマイズ性が高い"],"pricing":{"monthlyBaseFee":0,"monthlyPricePerUser":19800}}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 2);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('hubspot_crm', 1, 'saas-product', 'saas', 'HubSpot CRM', '無料枠から始められるCRM。マーケティング機能との連携に強みがある', '{"strengths":["低コストで開始できる","マーケティング機能と統合できる","UIが使いやすい"],"pricing":{"monthlyBaseFee":0,"monthlyPricePerUser":3000}}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 3);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('coubic_stores_reserve', 1, 'saas-product', 'saas', 'STORES 予約 / Coubic', '日時・リソース予約に特化した国産SaaS。空き枠管理や自動通知が標準機能', '{"strengths":["予約管理に特化している","低コストで導入できる","決済連携も可能"],"pricing":{"monthlyBaseFee":8000,"monthlyPricePerUser":0}}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 4);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('logizard_zero', 1, 'saas-product', 'saas', 'ロジザードZERO', '倉庫在庫管理に特化した国産SaaS。ハンディ端末連携も標準対応', '{"strengths":["在庫管理に特化している","ハンディ端末に対応","国内導入実績が豊富"],"pricing":{"monthlyBaseFee":30000,"monthlyPricePerUser":0}}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 5);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('notion_qast', 1, 'saas-product', 'saas', 'Notion / Qast', '社内ナレッジの蓄積・共有に特化したSaaS。近年はAI検索機能も強化されている', '{"strengths":["導入が容易","検索性が高い","社内Wikiとして定着しやすい"],"pricing":{"monthlyBaseFee":0,"monthlyPricePerUser":1200}}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 6);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('zendesk', 1, 'saas-product', 'saas', 'Zendesk', '問い合わせ対応・チケット管理の定番SaaS。API/Webhookでの外部連携が豊富', '{"strengths":["外部連携APIが豊富","マルチチャネル対応","導入実績が豊富"],"pricing":{"monthlyBaseFee":0,"monthlyPricePerUser":7000}}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 7);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('power_automate_zapier', 1, 'saas-product', 'saas', 'Power Automate / Zapier', 'SaaS間のデータ連携・自動化に特化したノーコードツール', '{"strengths":["ノーコードで連携を構築できる","対応SaaSコネクタが多い","低コストで開始できる"],"pricing":{"monthlyBaseFee":10000,"monthlyPricePerUser":0}}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 8);
INSERT INTO registry_technologies (id, release_id, category_id, technology_kind, name, description, details_json, security_score, cost_score, development_speed_score, ai_coding_score, scalability_score, status, notes, sort_order) VALUES ('looker_studio', 1, 'saas-product', 'saas', 'Looker Studio', '複数データソースを無料で可視化できるダッシュボードSaaS', '{"strengths":["無料で始められる","多様なデータソースに接続できる","共有が容易"],"pricing":{"monthlyBaseFee":0,"monthlyPricePerUser":0}}', NULL, NULL, NULL, NULL, NULL, 'active', NULL, 9);
